exclude: '^$'
fail_fast: false
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.6.9'
    hooks:
      - id: ruff
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.10' # Update me!
    hooks:
      - id: bandit
        args: [--ini, .bandit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.11.2'  # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        additional_dependencies:
          - types-docutils
          - types-setuptools
          - types-PyYAML
          - types-requests
        args: ["--python-version", "3.10", "--ignore-missing-imports"]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3
ci:
  # To trigger manually, comment on a pull request with "pre-commit.ci autofix"
  autofix_prs: false
  autoupdate_schedule: "monthly"
  skip: [bandit]
